[env]
APP_ENV = "dev"
SERVER_PORT = 8000
DEBUG_LEVEL = "DEBUG"

[tasks."dev:create-image"]
run = 'podman build -t docker.io/tasuki/pi-rtgo:latest -f Containerfile.dev .'
[tasks."client-config"]
dir = "client"
run = "cp config.${APP_ENV}.gleam src/config.gleam"
[tasks."dev:server"]
dir = "server"
run = """
watchexec --restart --verbose \
  --wrap-process=session --exts=gleam --debounce=100ms \
  -- gleam run
"""
[tasks."dev:client"]
depends = ["client-config"]
dir = "client"
run = "gleam run -m lustre/dev start"
[tasks.dev]
depends = ["dev:server", "dev:client"]

[tasks.build]
run = [
  "cd shared && gleam build",
  "cd server && gleam build",
  "cd client && gleam build",
  "ln -sf ../../../packages/lustre/priv client/build/dev/javascript/lustre/",
  "ln -sf ../../../packages/lustre_dev_tools/priv client/build/dev/javascript/lustre_dev_tools/",
]

[tasks."test:shared"]
dir = "shared"
run = "gleam test"
[tasks."test:server"]
dir = "server"
run = "gleam test"
[tasks.test]
depends = ["test:shared", "test:server"]
